[build]
base = "."
publish = "site"
command = """
pip3 install --user uv && 
export PATH=$PATH:$HOME/.local/bin && 
uv sync --no-dev --group docs && 
uv run --active --no-sync mkdocs build --strict
"""
